[project]
name = "seance2-json-xml"
version = "0.1.0"
description = "Traitement de donnÃ©es JSON et XML"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
